#!/usr/bin/env node
/*
 * Bundles index.html + style.css + game.js into single self-contained files.
 *
 *   node build.js
 *
 * Outputs:
 *   dist/blockbrawl.html    complete standalone page — open it directly,
 *                           email it, or drop it on any static host
 *   dist/embed.html         the same page without the <!DOCTYPE>/<html>/<head>/
 *                           <body> wrapper, for hosts that supply their own
 *
 * Nothing here is minified on purpose: the output stays readable and diffable.
 */

const fs = require('fs');
const path = require('path');

const root = __dirname;
const outDir = path.join(root, 'dist');

const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'style.css'), 'utf8');
const js = fs.readFileSync(path.join(root, 'game.js'), 'utf8');

const banner = '<!-- 方塊對戰 Block Brawl — generated by build.js, do not edit by hand.\n'
  + '     Source: index.html + style.css + game.js -->';

// Swap the external references for the real thing.
const inlined = html
  .replace(/[ \t]*<link rel="stylesheet" href="style\.css">\n?/,
    '<style>\n' + css.trimEnd() + '\n</style>\n')
  .replace(/[ \t]*<script src="game\.js"><\/script>\n?/,
    '  <script>\n' + js.trimEnd() + '\n  </script>\n');

if (inlined.includes('style.css') || inlined.includes('game.js')) {
  console.error('build failed: index.html no longer matches the expected <link>/<script> tags');
  process.exit(1);
}

const standalone = inlined.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n' + banner);

// The embed build drops the document wrapper but keeps <title>, <style> and
// the body content, which is what an embedding host expects to receive.
const head = inlined.match(/<head>([\s\S]*?)<\/head>/)[1];
const body = inlined.match(/<body>([\s\S]*?)<\/body>/)[1];
const title = head.match(/<title>[\s\S]*?<\/title>/)[0];
const style = head.match(/<style>[\s\S]*?<\/style>/)[0];

const embed = [banner, title, style, body.trim(), ''].join('\n');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'blockbrawl.html'), standalone);
fs.writeFileSync(path.join(outDir, 'embed.html'), embed);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
console.log('dist/blockbrawl.html  ' + kb(standalone));
console.log('dist/embed.html       ' + kb(embed));
